Fix config for tests
kpi-web-guild/django-girls-blog-makkaronis4e pull request #14
Opened 2017-12-26 17:37 UTC by makkaronis4e

Fix manage.py and pre-commit config
Fix #13

2017-12-26 17:55 UTC, webknjaz requested changes
Mixed changes

2017-12-26 20:26 UTC, webknjaz commented
> Fix config for tests

It's a lie: you need to make code PEP257-compliant

2017-12-26 20:37 UTC, webknjaz commented
@makkaronis4e 

here's a few docs for you to read:
- [ ] https://www.python.org/dev/peps/pep-0257/
- [ ] http://blog.dolphm.com/pep257-good-python-docstrings-by-example/

Also, exclude migrations folder from pep257 check.

2017-12-26 20:41 UTC, webknjaz commented
> `feature/fix-config`

You should've used `feature/13-fix-config` as per convention you agreed to follow in #8

2017-12-26 21:52 UTC, webknjaz commented on .pre-commit-config.yaml
> +  exclude: blog/migrations/
for this to work you should indent it by 2 spaces

2017-12-26 21:52 UTC, webknjaz commented on .pre-commit-config.yaml
> +  exclude: blog/migrations/
same as above

2017-12-27 08:14 UTC, webknjaz requested changes
And get rid of bogus commits.

2017-12-27 08:14 UTC, webknjaz commented on .pre-commit-config.yaml
> +
plz remove one line here.

2017-12-27 08:15 UTC, webknjaz commented on manage.py
> +"""Script for managing django."""
..app

2017-12-27 08:15 UTC, webknjaz commented on mysite/__init__.py
> +"""Configure files for site."""
Why is it in actionable mood?

2017-12-27 08:16 UTC, webknjaz commented on mysite/urls.py
> +"""mysite URL Configuration."""
what is mysite here?

2017-12-27 08:16 UTC, webknjaz commented on blog/models.py
> +    """Configuration of the post class."""
It's not configuration, and it's not for class. It's a model definition.

2017-12-27 08:17 UTC, webknjaz commented on blog/apps.py
> +"""Configuration module for blog."""
No, it's an apps config.

2017-12-27 08:18 UTC, webknjaz commented on blog/models.py
> +"""Models configuration in blog."""
It's not a config, but a description for models for interfacing with the DB.

2017-12-27 08:20 UTC, webknjaz commented on blog/admin.py
> +"""Admin panel registration."""
No, it's configuration for admin panel.

2017-12-27 08:26 UTC, webknjaz commented on blog/__init__.py
> +"""Configure files for blog."""
It should not be in imperative mood: just importing this package won't emit any actions. This is a description, no a command.

2017-12-27 08:29 UTC, webknjaz commented on blog/models.py
> +        """Return title of the post."""
@makkaronis4e in Python, "dunder methods" (wrapped w/ double underscores, also known as "magic methods") are special methods responsible for certain behaviours of objects.
`obj.__str__()` is called if the object is being stringified, for example using `str(obj)`, meaning rendering the object into a string representation.

That said, the docstring would be smth like `Render the post instance from its title.`

2017-12-27 17:11 UTC, webknjaz requested changes
- [ ] Improve PR name
- [ ] Make commit messages reflect their contents

2017-12-27 18:05 UTC, webknjaz commented on blog/tests.py
> +"""Test for ptoject."""
Typo: `ptoject`

2017-12-27 18:09 UTC, webknjaz commented on blog/tests.py
> +"""Test for ptoject."""
Test suite for the project.

2017-12-27 18:19 UTC, webknjaz requested changes
It looks better now, but there's still a few nitpicks, I'd like you to fix :)

2017-12-27 18:19 UTC, webknjaz commented on mysite/__init__.py
> +"""Configuration files for site."""
Not files: python operates such things as modules and packages. Also config files are normally some structured text files, which *don't contain any code*.

2017-12-27 18:19 UTC, webknjaz commented on blog/models.py
> +    """Definition of the model."""
I see that from the line above as it inherits model. Don't refer to implementation details, unless they really matter + don't repeat smth obvious one can notice w/o a docstring.
Better tell me that it's a blog post structure declaration.

2017-12-27 18:19 UTC, webknjaz commented on blog/__init__.py
> +"""Configuration files for blog."""
It's not files.

2017-12-27 20:52 UTC, makkaronis4e commented
@webknjaz Done

2017-12-27 21:08 UTC, webknjaz requested changes

2017-12-27 21:08 UTC, webknjaz commented on blog/views.py
> +"""Views configuration for blog."""
It's not config. It's just views.

2017-12-27 21:08 UTC, webknjaz commented on blog/__init__.py
> +"""Configuration for blog."""
It is not a config.

2017-12-27 21:08 UTC, webknjaz commented on mysite/__init__.py
> +"""Configuration for site."""
It's not a config. It is an app.

2017-12-27 21:50 UTC, webknjaz commented on blog/__init__.py
> +"""Configuration for blog."""
`Django blog app`

2017-12-27 21:50 UTC, webknjaz commented on blog/views.py
> +"""Views configuration for blog."""
`View for the blog app.`

2017-12-27 21:51 UTC, webknjaz commented on mysite/__init__.py
> +"""Configuration for site."""
`Mysite Django app.`

2017-12-27 22:02 UTC, webknjaz commented on manage.py
> +        import django # noqa: F401
@makkaronis4e fix this.

2017-12-27 23:25 UTC, webknjaz approved these changes

2017-12-27 23:27 UTC, merged