Improve project structure and add instructions for deployment
kpi-web-guild/django-girls-blog-makkaronis4e pull request #20
Opened 2018-01-01 20:29 UTC by makkaronis4e

Add requirements folder and improve readme

2018-01-01 20:29 UTC, makkaronis4e commented
@webknjaz new PR

2018-01-01 20:36 UTC, webknjaz requested changes
Spell `requirements` lowercase

2018-01-01 20:36 UTC, webknjaz commented on README.md
> +How to deploy this site from your own computer:
Add instructions for running locally

2018-01-01 20:36 UTC, webknjaz commented on README.md
> +4. Login to Heroku ```$ login heroku```
Code blocks should go to the separate line

2018-01-01 20:36 UTC, webknjaz commented on Requirements/prod.txt
> +psycopg2==2.7.3
You should include common config.

2018-01-01 20:36 UTC, webknjaz commented on Requirements/base.txt
> +aspy.yaml==1.0.0
Most of the the packages here are indirect, recall ones you installed explicitly and remove the rest of them.

2018-01-01 22:41 UTC, webknjaz commented on README.md
> +2. Print in browser
Not print, but open. You can also convert this into a clickable link (see Markdown syntax)

2018-01-01 22:42 UTC, webknjaz commented on README.md
> +1. Run your local server
Describe downloading the repo and setting up env (dependencies)

2018-01-01 22:42 UTC, webknjaz commented on README.md
> +How to run this site from your own computer locally and deploy it on heroku?
Mark this as title (5 hashes, for example; see Markdown)

2018-01-01 22:44 UTC, webknjaz commented on Requirements/base.txt
> +gunicorn==19.7.1
This is a prod dep

2018-01-01 22:45 UTC, webknjaz commented on Requirements/base.txt
> +flake8==3.5.0
This dep is for dev env, but I would say you don't need this, since it's managed separately by pre-commit tool

2018-01-01 22:45 UTC, webknjaz commented on Requirements/base.txt
> +pre-commit==1.4.1
This is definitely not needed in production

2018-01-01 22:46 UTC, webknjaz commented on Requirements/base.txt
> +pyflakes==1.6.0
It's a dev dep

2018-01-01 22:46 UTC, webknjaz commented on Requirements/base.txt
> +virtualenv==15.1.0
This should not be in the env at all

2018-01-01 22:48 UTC, webknjaz commented on Requirements/base.txt
> +whitenoise==3.3.1
This is likely a prod dep, but needs testing.

2018-01-01 22:49 UTC, webknjaz commented on requirements.txt
> -aspy.yaml==1.0.0
keep this file including prod dep via `-r`, it's needed for heroku

2018-01-01 22:50 UTC, webknjaz requested changes
Lowercase requirements

2018-01-02 18:52 UTC, webknjaz requested changes

2018-01-02 18:52 UTC, webknjaz commented on README.md
> +#####How to run this site from your own computer locally and deploy it on heroku?
Add space next to hashes

2018-01-02 18:52 UTC, webknjaz commented on README.md
> +```pip install -r dev.txt```
Triple quotes should be on separate lines

2018-01-02 18:52 UTC, webknjaz commented on README.md
> +```http://127.0.0.1:8000/```
Still not a link

2018-01-02 18:52 UTC, webknjaz commented on README.md
> +``` $ heroku auth:token```
You don't normally need a token with ssh key

2018-01-02 18:52 UTC, webknjaz commented on mysite/settings.py
> +        'USER': 'mak',
This all should be taken from env via dj_database_url

2018-01-02 18:52 UTC, webknjaz commented on requirements/base.txt
> +gunicorn==19.7.1
Not dev

2018-01-02 18:52 UTC, webknjaz commented on requirements/base.txt
> +psycopg2==2.7.3
Not dev

2018-01-02 18:52 UTC, webknjaz commented on requirements/prod.txt
> +-r base.txt
Do you need django in production?

2018-01-02 18:52 UTC, webknjaz commented on requirements/reqruirements.txt
> +
This line is not needed + move this file to the root folder

2018-01-02 20:28 UTC, webknjaz approved these changes

2018-01-02 20:29 UTC, merged