Integrate env vars based config
kpi-web-guild/django-girls-blog-makkaronis4e pull request #21
Opened 2018-01-03 17:47 UTC by makkaronis4e

Integrate env vars based config

2018-01-03 22:54 UTC, webknjaz requested changes

2018-01-03 22:54 UTC, webknjaz commented on README.md
>  DEBUG = True
No, it shouldn't contain spaces. Better add example file to the repo as I advised you earlier.

2018-01-04 17:13 UTC, makkaronis4e commented
@webknjaz Done

2018-01-04 17:17 UTC, webknjaz approved these changes

2018-01-04 17:30 UTC, merged