Add new options and class based views
kpi-web-guild/django-girls-blog-makkaronis4e pull request #29
Opened 2018-01-10 09:47 UTC by makkaronis4e

Add class based views.
Add comments, login-form, login/logout functionality.

2018-01-13 18:23 UTC, makkaronis4e commented
@webknjaz done

2018-01-19 18:34 UTC, webknjaz commented on .vscode/settings.json
> +    "python.formatting.provider": "yapf"
this one is horrible

2018-01-21 19:12 UTC, webknjaz requested changes

2018-01-21 19:12 UTC, webknjaz commented on blog/views.py
> +class PublishPost(Protected, TemplateView):
Inheritance order is incorrect.

2018-01-21 19:12 UTC, webknjaz commented on blog/views.py
> +class NewPost(FormView, Protected):
This breaks redirection.

2018-01-21 19:12 UTC, webknjaz commented on blog/views.py
> +from django.shortcuts import get_object_or_404, redirect
You don't need these.

2018-01-21 19:12 UTC, webknjaz commented on blog/views.py
> +class AddCommentToPost(FormView):
Use `CreateView`

2018-01-21 19:12 UTC, webknjaz commented on blog/views.py
> +    def post(self, request, *args, **kwargs):
Drop this

2018-01-21 19:12 UTC, webknjaz commented on blog/views.py
> +        comment.approve()
According to `HTTP` spec, `GET` method is idempotent, i.e. it MUSTN'T change the resource it represents (or trigger any other actions within system). You should use either of `PUT`, `PATCH` or `POST` for this purpose.

2018-01-21 19:12 UTC, webknjaz commented on blog/views.py
> +class ApproveComment(Protected, TemplateView):
TemplateView shouldn't be used for redirects, but for showing some representation.

2018-01-21 19:12 UTC, webknjaz commented on blog/views.py
> +    def post(self, request, *args, **kwargs):
Drop this, let DeleteView handle logic.

2018-01-21 19:12 UTC, webknjaz commented on blog/tests/test_models.py
>          self.assertEqual(self.test_post.published_date, datetime(day=1, month=4, year=2016,
Where's teardown of this test suite?

2018-02-16 20:02 UTC, makkaronis4e commented on blog/tests/test_models.py
>          self.assertEqual(self.test_post.published_date, datetime(day=1, month=4, year=2016,
Done

2018-02-18 11:45 UTC, webknjaz approved these changes

2018-02-18 11:45 UTC, merged