Class based views
kpi-web-guild/django-girls-blog-makkaronis4e pull request #30
Opened 2018-01-13 18:11 UTC by makkaronis4e

Add class based views

2018-01-13 18:23 UTC, makkaronis4e commented
@webknjaz done

2018-01-14 08:12 UTC, webknjaz requested changes

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
> +    """Show all your Post objects."""
Your? Whom is it talking about?

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
> +    @method_decorator(login_required)
Did it work like this before rewrite?

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
> +    """Return page for adding new Post."""
Don't use actionable verbs in class docstring as it describes some entity, not an action.

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
>          form = PostForm(request.POST)
You shouldn't need to initialize your own form instance. It should be pre-populated by internal CBV machinery and available as `self.form`

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
>          if form.is_valid():
`post()` method will only be called if it's valid (based on the `form_valid()` method call earlier), so this check is also useless.

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
> +    def post(self, request, *args, **kwargs):
I bet `post()` method does not accept request as an argument. args/kwargs also look unrealistic

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
>              post.author = request.user
You already do this in `form_valid()` method

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
>              return redirect('post_detail', pk=post.pk)
Based on above, I'd say that it is never called. success_url is used instead.

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
>              post.save()
And this of course is done by CBV as well

2018-01-14 08:12 UTC, webknjaz commented on blog/views.py
> +    success_url = reverse_lazy('post_list')
You'd better redirect to post

2018-01-15 00:17 UTC, webknjaz requested changes

2018-01-15 00:17 UTC, webknjaz commented on blog/views.py
> +    def post(self, request, *args, **kwargs):
So remove it.

2018-01-19 18:31 UTC, webknjaz approved these changes

2018-01-19 18:32 UTC, merged